### ISSUE TITLE
TODO - Pure-2B

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE1x.jl#2]
- [x] deleting the 2b currently just sets the CC = 0, but need to actually remove this from the basis so we don't get 0-basis functions. 
- [x] link the product-Rn coefficients to entries of AA rather than *assuming* what they will be 
- [x] the last part of the `c_nnll` scaling factor should come from the AA evaluation and not be guessed
- [x] extend to multi-species
- [x] Will's multi-species radial basis 
- [ ] need a test that determines whether the new basis is equivalent to the old.

**Comment by cortner** [comment]
First of the remaining items will be taken care of via the discussion in  #8 . 

To wrap this up, what would be a good test to check the equivalence?

**Comment by cortner** [comment]
all of this has been done. And since the new basis is NOT equivalent to the old we can skip that step.
